runtime: python313
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  # Optional: Override default GCS bucket
  # GCS_BUCKET: "my-custom-bucket"

  # Cloud Tasks configuration
  CLOUD_TASKS_LOCATION: "us-central1"

handlers:
- url: /static
  static_dir: static

- url: /_ah/pipeline(/.*)?
  script: auto

- url: .*
  login: required
  script: auto
