application: pipeline-test
version: 1
runtime: python39
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /_ah/pipeline(/.*)?
  script: main.py

- url: .*
  login: required
  script: main.py
