steps:
  - name: 'python:3.9.4'
    dir: /workspace/python
    script: |
      #!/usr/bin/env bash
      pip install -r requirements.txt --user
    id: "install-dependencies"

  - name: 'python:3.9.4'
    dir: /workspace/python
    script: |
      #!/usr/bin/env bash
      python3 -m pytest
    id: "test"

  - name: 'python:3.9.4'
    dir: /workspace/python
    script: |
      #!/usr/bin/env bash
      # Build sdist and wheel from src/
      python3 -m build src --sdist --wheel --outdir dist/
      python3 -m twine upload --repository-url https://us-central1-python.pkg.dev/repcore-prod/python/ dist/*
    id: "publish"
