steps:
  - name: 'python:3.9.4'
    dir: /workspace/python
    script: |
      #!/usr/bin/env bash
      pip install -r requirements.txt --user
    id: "install-dependencies"

  - name: 'python:3.9.4'
    dir: /workspace/python
    script: |
      #!/usr/bin/env bash
      python3 -m pytest
    id: "test"
