steps:
  - name: 'python:3.13'
    dir: /workspace/python
    script: |
      #!/usr/bin/env bash
      pip install --prefer-binary -r requirements.txt --user
    id: "install-dependencies"

  - name: 'python:3.13'
    dir: /workspace/python
    script: |
      #!/usr/bin/env bash
      python3 -m pytest
    id: "test"
    waitFor: [ 'install-dependencies' ]
